const profiles = {
    developers: [
        {
            userId: 2531,
            name: 'Fred',
            skills: [
                'Typescript',
                'Javascript',
                'Golang',
                'Python',
                'AWS',
                'Azure',
                'Svelte',
            ],
            color: '#727896',
            roles: 'Junior',
        },
        {
            userId: 2584,
            name: 'John',
            skills: ['Rust', 'Golang', 'SQL', 'AWS', 'Azure'],
            color: '#77A5A5',
            roles: 'Senior',
        },
        {
            userId: 2249,
            name: 'Harlan',
            skills: ['Python', 'SQL', 'AWS', 'Azure'],
            color: '#C4CFBE',
            roles: 'Medior',
        },
        {
            userId: 2295,
            name: 'James',
            skills: ['Python', 'PHP', 'SQL', 'AWS', 'Azure'],
            color: '#F0DBC7',
            roles: 'Management',
        },
        {
            userId: 1903,
            name: 'Louis',
            skills: [
                'Typescript',
                'Golang',
                'PHP',
                'SQL',
                'Azure',
                'Vue',
                'Svelte',
            ],
            color: '#C89E9E',
            roles: 'Consultant',
        },
        {
            userId: 4971,
            name: 'Lucas',
            skills: [
                'Typescript',
                'Javascript',
                'Rust',
                'Webassembly',
                'React',
                'Vue',
                'Svelte',
                'Angular',
            ],
            color: '#C89E9E',
            roles: 'Senior+',
        },
        {
            userId: 8972,
            name: 'Thijmen',
            skills: ['Typescript', 'Javascript', 'React', 'Vue', 'Svelte'],
            color: '#727896',
            roles: 'Junior',
        },
        {
            userId: 8362,
            name: 'Jacky',
            skills: [
                'Python',
                'SQL',
                'AWS',
                'Azure',
                'Data-engineer',
                'Dev-ops',
            ],
            color: '#77A5A5',
            roles: 'Junior',
        },
    ],
};

export default profiles;
